//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWeb.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hutuch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hutuch()
        {
            this.Hutulburs = new HashSet<Hutulbur>();
        }
    
        public int hutuchId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string registerNo { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public System.DateTime birthDate { get; set; }
        public bool gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hutulbur> Hutulburs { get; set; }
    }
}
