//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWeb.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hutulbur
    {
        public int hutulburId { get; set; }
        public string name { get; set; }
        public string chiglel { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string taniltsuulga { get; set; }
        public string zurag { get; set; }
        public int hutuchId { get; set; }
    
        public virtual Hutuch Hutuch { get; set; }
    }
}
